[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.hints.end]
background = "#1d1f21"
foreground = "#e9ff5e"

[colors.hints.start]
background = "#e9ff5e"
foreground = "#1d1f21"

[colors.primary]
background = "#1d1f21"
bright_foreground = "#eaeaea"
dim_foreground = "#828482"
foreground = "#c5c8c6"

# [colors.search.bar]
# background = "#c5c8c6"
# foreground = "#1d1f21"

[colors.search.focused_match]
background = "#000000"
foreground = "#ffffff"

[colors.search.matches]
background = "#ffffff"
foreground = "#000000"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[font]
size = 12.0
# size = 6.0

[font.bold]
family = "SauceCodePro Nerd Font Mono"
style = "Bold"
# family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "SauceCodePro Nerd Font Mono"
style = "Bold Italic"
# family = "JetBrainsMono Nerd Font"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "SauceCodePro Nerd Font Mono"
style = "Italic"
# family = "JetBrainsMono Nerd Font"

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"
# family = "JetBrainsMono Nerd Font"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_padding = false
opacity = 0.78

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 4
y = 4
